packages:
  - 'common/tools/dev-tool'
  - 'common/tools/eslint-plugin-azure-sdk'
  - 'common/tools/eslint-plugin-azure-sdk-helper'
  - 'common/tools/vite-plugin-browser-test-map'
  - 'sdk/core/abort-controller'
  - 'sdk/core/core-amqp'
  - 'sdk/core/core-auth'
  - 'sdk/core/core-client'
  - 'sdk/core/core-client-rest'
  - 'sdk/core/core-http-compat'
  - 'sdk/core/core-lro'
  - 'sdk/core/core-paging'
  - 'sdk/core/core-rest-pipeline'
  - 'sdk/core/core-sse'
  - 'sdk/core/core-tracing'
  - 'sdk/core/core-util'
  - 'sdk/core/core-xml'
  - 'sdk/core/logger'
  - 'sdk/core/perf-tests/core-rest-pipeline'
  - 'sdk/core/ts-http-runtime'
  - 'sdk/test-utils/recorder'
  - 'sdk/test-utils/test-credential'
  - 'sdk/test-utils/test-utils'
  - 'sdk/test-utils/test-utils-vitest'
  - 'sdk/advisor/arm-advisor'
  - 'sdk/agrifood/agrifood-farming-rest'
  - 'sdk/agrifood/arm-agrifood'
  - 'sdk/ai/ai-inference-rest'
