trigger: none

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      PackageName: "@azure/app-configuration"
      ServiceDirectory: appconfiguration
      SupportedClouds: 'Public,UsGov,China'
      UseFederatedAuth: true
      CloudConfig: 
        Public:
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ServiceConnection: azure-sdk-tests
          # SubscriptionConfigurationFilePaths:
          #   - eng/common/TestResources/sub-config/AzurePublicMsft.json
