parameters:
  - name: ServiceDirectory
    type: string
    default: not-specified
  - name: TestProxy
    type: boolean
    default: true
  - name: Artifacts
    type: object
    default: []
  - name: Matrix
    type: string
  - name: DependsOn
    type: object
    default: []
  - name: UsePlatformContainer
    type: boolean
    default: false
  - name: CloudConfig
    type: object
    default: {}
  - name: OSName
    type: string
    default: ''

jobs:
  - job:
    displayName: 'UnitTest'

    condition: |
      and(
        succeededOrFailed(),
        ne(variables['Skip.Test'], 'true'),
        ne(${{ parameters.Matrix }}, '{}')
      )

    dependsOn:
       - ${{ parameters.DependsOn }}

    strategy:
      matrix: $[ ${{ parameters.Matrix }} ]

    pool:
      name: $(Pool)
      vmImage: $(OSVmImage)
      os: ${{ parameters.OSName }}
    ${{ if eq(parameters.UsePlatformContainer, 'true') }}:
      # Add a default so the job doesn't fail when the matrix is empty
      container: $[ variables['Container'] ]

    variables:
      - template: ../variables/globals.yml

    steps:
      - template: ../steps/common.yml

      - template: ../steps/test.yml
        parameters:
          Artifacts: ${{ parameters.Artifacts }}
          ServiceDirectory: ${{ parameters.ServiceDirectory }}
          TestProxy: ${{ parameters.TestProxy }}
          OSName: ${{ parameters.OSName }}
